#%RAML 1.0 NamedExample
value:
  -  
    firstName: Derek
    lastName: Shepherd
    address: Richmond
    postal: 3121
    country: Australia
    miles: 236
    type: business
  -
    firstName: Meredith
    lastName: Grey
    address: Seattle
    postal: 98101
    country: USA
    miles: 101
    type: personal